views/homepage.py
from flask import Blueprint, render_template, redirect, url_for, request

from database.database import session_maker, Typ_stroje, Stroj
from forms import ObjednavkaForm, SearchForm

homepage = Blueprint('homepage', __name__)

@homepage.route('/', methods=['GET', 'POST'], endpoint='home')
def home():
    form = ObjednavkaForm()
    search_form = SearchForm()
    results = []

    # ziskani hodnot typ stroje z databaze
    typ_stroje_values = session_maker.query(Typ_stroje.typ_stroje_nazev).distinct().all()
    # dynamicke nastaveni hodnot typu stroje do atributu dropboxu - choices
    search_form.type.choices = [(value.typ_stroje_nazev, value.typ_stroje_nazev) for value in typ_stroje_values]

    if request.method == 'POST' and search_form.validate_on_submit():

        typ = form.type.data
        datum_od = form.date_from.data
        datum_do = form.date_to.data

        pass

    # Kontrola, zda byl formulář odeslán
    if form.is_submitted():
        typ = form.typ.data
        datum_od = form.datum_od.data
        datum_do = form.datum_do.data

        # Vytvoření dotazu do databáze na základě zadaných údajů
        query = (
            session_maker.query(Stroj)
            .join(Typ_stroje, Typ_stroje.typ_stroje_id == Stroj.typ_stroje_id)
            .filter(
                Typ_stroje.typ_stroje_nazev == typ,
            )
        )

        # Získání výsledků dotazu
        results = query.all()

    # Vrátí šablonu index.jinja s předanými daty
    return render_template('homepage/index.jinja', form=form, search_form=search_form, results=results)

@homepage.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if request.method == 'POST' and form.validate_on_submit():

        typ = form.type.data
        datum_od = form.date_from.data
        datum_do = form.date_to.data

    return redirect(url_for('order.nabidka_stroju'))

templates/homepage/index.jinja
{% extends '/__main.jinja' %}

{% block content %}

    <!--Uvodni sekce-->
    <div class="hero-section">
        <div class="hero-text">
            <h1>Půjčovna strojů</h1>
            <h2>Zadejte vaše preference a doručíme vám stroj do druhého dne</h2>
        </div>
{#        <div class="form-section">#}
{#             <!--<form id="filter-form" method="POST" action="{{ url_for('homepage.home') }}">-->#}
{#            <div class="input-group">#}
{#                <label for="machine-type">Typ stroje:</label>#}
{#                <select id="machine-type">#}
{#                    <option value="default">Vyberte typ stroje</option>#}
{#                    <!-- Vyplnění zápisy z tabulky Typ_stroje -->#}
{#                    {% for typ_stroje_value in typ_stroje_values %}#}
{#                    <option value="{{ typ_stroje_value }}">{{ typ_stroje_value }}</option>#}
{#                    {% endfor %}#}
{#                </select>#}
{#            </div>#}
{#            <div class="input-group">#}
{#                <label for="date-from">Od kdy:</label>#}
{#                <input type="date" id="date-from">#}
{#            </div>#}
{#            <div class="input-group">#}
{#                <label for="date-to">Do kdy:</label>#}
{#                <input type="date" id="date-to">#}
{#            </div>#}
{#            <button type="submit">OK</button>#}
{#             <!--</form>-->#}
{#            <div class="error-message"></div>#}
{#        </div>#}

        <div class="form-section">
            <form action="{{ url_for('homepage.search') }}" method="post">
                {{ search_form.hidden_tag() }}
                <div class="input-group">
                    {{ search_form.type.label }}
                    {{ search_form.type(id="machine-type") }}
                </div>
                <div class="input-group">
                    {{ search_form.date_from.label }}
                    {{ search_form.date_from(id="date-from") }}
                </div>
                <div class="input-group">
                    {{ search_form.date_to.label }}
                    {{ search_form.date_to(id="date-to") }}
                </div>
                <div>
                    {{ search_form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>

    <!--Jak to funguje sekce-->
    <div class="jak-to-fuguje">
        <h1>Jak to funguje?</h1>
        <div class="info-boxes">
            <div class="info-box">
                <div class="icon"><i class="fas fa-search"></i></div>
                <h3>Výběr stroje</h3>
                <p>Vyberte si stroj, který nejlépe vyhovuje vašim potřebám.</p>
            </div>
            <div class="info-box">
                <div class="icon"><i class="fas fa-calendar-alt"></i></div>
                <h3>Rezervace termínu</h3>
                <p>Zvolte datum, kdy chcete stroj půjčit.</p>
            </div>
            <div class="info-box">
                <div class="icon"><i class="fas fa-truck"></i></div>
                <h3>Doručení stroje</h3>
                <p>Stroj vám doručíme přímo na místo určení.</p>
            </div>
        </div>
    </div>

    <!--O nas sekce-->
    <div class="o-nas" id="o-nas">
        <div class="text-content">
            <h1>O nás</h1>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing
                elit.
                Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nunc tincidunt ante vitae massa. Mauris
                dictum facilisis augue.
                Etiam neque. Praesent vitae arcu tempor neque lacinia pretium. Duis pulvinar. Sed ut perspiciatis unde omnis
                iste natus error sit
                voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis
                et quasi architecto beatae
                vitae dicta sunt explicabo. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor
                sit amet purus malesuada congue.
                Nullam sit amet magna in magna gravida vehicula. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum
                at dui. In convallis.
                Mauris elementum mauris vitae tortor. </p>
        </div>
        <div class="image-content">
            <img src="/static/images/o-nas-image.jpg">
        </div>
    </div>
{% endblock %}