views/order.py
from flask import *
from forms import *
from database.database import *
import datetime

order = Blueprint('order', __name__)

#Výpis strojů
@order.route('/nabidka-stroju', methods=['GET', 'POST'])
def nabidka_stroju():
    if request.method == 'POST':
        # Zpracování formuláře pro výběr a objednání stroje
        if 'stroj_id' in request.form:
            # Získání dat z formuláře
            stroj_id = request.form['stroj_id']
            datum_od_str = request.form['datum_od']
            datum_do_str = request.form['datum_do']
            ucet_id = request.form['ucet_id']

            datum_od = datetime.datetime.strptime(datum_od_str, '%Y-%m-%d').date()
            datum_do = datetime.datetime.strptime(datum_do_str, '%Y-%m-%d').date()

            # Vytvoření nové objednávky
            new_objednavka = Objednavka(
                objednavka_id = None,
                objednavka_datum_od = datum_od,
                objednavka_datum_do = datum_do,
                stroj_id = stroj_id,
                ucet_id=ucet_id
            )

            # Přidání objednávky do databáze a potvrzení
            session_maker.add(new_objednavka)
            session_maker.commit()

        # Filtrování strojů podle zvoleného typu
        selected_type = request.form.get('machine-type')
        if selected_type and selected_type != 'default':
            stroje = session_maker.query(Stroj).join(Typ_stroje).filter(Typ_stroje.typ_stroje_id == int(selected_type)).all()
        else:
            stroje = session_maker.query(Stroj).all()

    else:
        stroje = session_maker.query(Stroj).all()

    # Vrátí šablonu nabidka-stroju.jinja s daty o strojích
    return render_template('order/nabidka-stroju.jinja', stroje=stroje)

@order.route('/objednavky-k-potvrzeni')
def objednavky_k_potvrzeni():
    # Dotaz do databáze pro získání všech objednávek
    objednavky = session_maker.query(Objednavka).all()

    # Získání ID objednávek s neplatnou rezervací
    zrusene_rezervace_id = [rez.objednavka_id for rez in session_maker.query(Rezervace).filter_by(rezervace_platnost=False).all()]

    # Vrátí šablonu objednavky-k-potvrzeni.jinja s daty o objednávkách
    return render_template('order/objednavky-k-potvrzeni.jinja', objednavky=objednavky, zrusene_rezervace=zrusene_rezervace_id)

# Vytvoření nového záznamu do tabulky Rezervace po přiřazení pracovníka dispečerem
@order.route('/vytvorit_rezervaci', methods=['POST'])
def vytvorit_rezervaci():
    # Přijetí JSON dat z požadavku
    data = request.json
    objednavka_id = data['objednavka_id']
    ucet_id = data['ucet_ids'][0]

    # Vytvoření nové rezervace
    new_rezervace = Rezervace(
        rezervace_id=None,
        rezervace_platnost=True,
        objednavka_id=objednavka_id,
        ucet_id=ucet_id
    )

    # Aktualizace stavu objednávky
    objednavka = session_maker.query(Objednavka).filter_by(objednavka_id=objednavka_id).first()
    if objednavka:
        objednavka.objednavka_zpracovana = True
        session_maker.commit()

    # Přidání rezervace do databáze
    session_maker.add(new_rezervace)
    session_maker.commit()

    # Vrátí potvrzení o úspěšném vytvoření rezervace ve formátu JSON
    return jsonify({'message': 'Rezervace uspesne vytvorena'})

# Zrušení rezervace uživatelem
@order.route('/zrusit_rezervaci', methods=['POST'])
def zrusit_rezervaci():
    # Získání ID rezervace z formuláře
    rezervace_id = request.form.get('rezervace_id')

    # Dotaz do databáze pro nalezení specifické rezervace
    rezervace_to_cancel = session_maker.query(Rezervace).filter_by(rezervace_id=rezervace_id).first()

    # Pokud byla rezervace nalezena, nastaví se jako neplatná
    if rezervace_to_cancel:
        # Po stisknuti tlačítka se rezervace oznaci jako False
        rezervace_to_cancel.rezervace_platnost = False
        session_maker.commit()

    # Přesměrování zpět na profil uživatele
    return redirect(url_for('profile.profil'))

# Zrušení objednávky dispečerem
@order.route('/zrusit_objednavku', methods=['POST'])
def zrusit_objednavku():
    # Získání ID objednávky z formuláře
    objednavka_id = request.form.get('objednavka_id')

    # Vyhledání a vymazání příslušné rezervace
    rezervace_to_delete = session_maker.query(Rezervace).filter_by(objednavka_id=objednavka_id).first()
    if rezervace_to_delete:
        session_maker.delete(rezervace_to_delete)

    # Vyhledání a vymazání objednávky
    objednavka_to_delete = session_maker.query(Objednavka).filter_by(objednavka_id=objednavka_id).first()
    if objednavka_to_delete:
        session_maker.delete(objednavka_to_delete)

    session_maker.commit()

    # Přesměrování na stránku s objednávkami k potvrzení
    return redirect(url_for('order.objednavky_k_potvrzeni'))

# Zobrazení zakázek přihlášeného uživatele
@order.route('/moje-zakazky')
def moje_zakazky():
    # Získání ID přihlášeného uživatele
    user_id = session.get('ucet_id')

    # Dotaz do databáze pro získání rezervací daného uživatele
    rezervace_zaznamy = session_maker.query(
        Rezervace.rezervace_id,
        Objednavka.objednavka_datum_od,
        Objednavka.objednavka_datum_do,
        Stroj.stroj_nazev
    ).join(Objednavka, Rezervace.objednavka_id == Objednavka.objednavka_id) \
     .join(Stroj, Objednavka.stroj_id == Stroj.stroj_id) \
     .filter(Rezervace.ucet_id == user_id).all()

    # Vrátí šablonu moje-zakazky.jinja s daty o rezervacích
    return render_template('order/moje-zakazky.jinja', rezervace_records=rezervace_zaznamy)

views/profile.py
from flask import *
from forms import *
from database.database import *
from werkzeug.security import check_password_hash

profile = Blueprint('profile', __name__)

#Přihlášení zákazníka
@profile.route('/prihlaseni', methods=['GET', 'POST'])
def prihlaseni():
    form_prihlaseni = SingupForm()

    # Zpracování formuláře po odeslání
    if request.method == 'POST' and form_prihlaseni.validate_on_submit():
        # Získání uživatelského jména a hesla z formuláře
        jmeno = form_prihlaseni.name.data
        heslo = form_prihlaseni.password.data

        # Hledání účtu v databázi
        ucet = session_maker.query(Ucet).filter_by(ucet_jmeno=jmeno).first()

        # Ověření hesla a přihlášení uživatele
        if ucet and check_password_hash(ucet.ucet_heslo, heslo):
            # Nastavení session proměnných
            session['user_name'] = jmeno
            session['ucet_id'] = ucet.ucet_id
            session['typ_uctu_id'] = ucet.typ_uctu_id
            print('Úspěšně přihlášen')
            # Přesměrování na domovskou stránku
            return redirect(url_for('homepage.home'))
        else:
            print('Nesprávné uživatelské jméno nebo heslo')

    # Vrátí šablonu prihlaseni.jinja s formulářem pro přihlášení
    return render_template('profile/prihlaseni.jinja', form=form_prihlaseni)

#Registrace zákazníka
@profile.route('/registrace', methods=['GET', 'POST'])
def registrace():
    form = RegisterForm()

    # Zpracování formuláře po odeslání
    if request.method == 'POST' and form.validate_on_submit():
        # Získání údajů z formuláře
        name = form.name.data
        email = form.email.data
        password = form.password.data

        # hashed_password = generate_password_hash(password)

        # Vytvoření nového účtu
        ucet_count = session_maker.query(Ucet).count()
        new_ucet_id = ucet_count + 1
        new_ucet = Ucet(new_ucet_id, ucet_jmeno=name, ucet_email=email, ucet_heslo=password, typ_uctu_id=3)

        # Přidání účtu do databáze a potvrzení
        session_maker.add(new_ucet)
        session_maker.commit()

        # Přesměrování na stránku pro přihlášení
        return redirect(url_for('profile.prihlaseni'))

    # Vrátí šablonu registrace.jinja s formulářem pro registraci
    return render_template('profile/registrace.jinja', form=form)

#Odhlášení zákazníka
@profile.route('/odhlaseni')
def odhlaseni():
    # Vyčištění session proměnných
    session.clear()
    # Přesměrování na domovskou stránku
    return redirect(url_for('homepage.home'))

# Vypisování potvrzených rezervací na stránce profil.jinja
@profile.route('/profil')
def profil():
    # Získání ID přihlášeného uživatele
    user_id = session.get('ucet_id')

    # Zpracování pouze pokud je uživatel přihlášen
    if user_id is not None:
        # Dotaz do databáze pro získání rezervací přihlášeného uživatele
        rezervace_zaznamy = session_maker.query(
            Rezervace,
            Objednavka.objednavka_datum_od,
            Objednavka.objednavka_datum_do,
            Stroj.stroj_nazev, Stroj.stroj_cena,
            Ucet.ucet_jmeno
        ).join(Objednavka, Rezervace.objednavka_id == Objednavka.objednavka_id) \
            .join(Stroj, Objednavka.stroj_id == Stroj.stroj_id) \
            .join(Ucet, Rezervace.ucet_id == Ucet.ucet_id) \
            .filter(Objednavka.ucet_id == user_id).all()

        # Výpočet celkové ceny za každou rezervaci
        zpracovane_zaznamy = []
        for zaznam in rezervace_zaznamy:
            hours = (zaznam[2] - zaznam[1]).total_seconds() / 3600
            fixed_cost = 150
            cena = int(zaznam[4] * hours + fixed_cost * hours)
            zpracovany_zaznam = tuple(zaznam) + (cena,)
            zpracovane_zaznamy.append(zpracovany_zaznam)

        # Vrátí šablonu profil.jinja s daty rezervací
        return render_template('profile/profil.jinja', rezervace_records=zpracovane_zaznamy)

    # Přesměrování na přihlášení, pokud uživatel není přihlášen
    return redirect(url_for('profile.prihlaseni'))

#Výpis pracovníků
@profile.route('/pracovnici')
def pracovnici():
    pracovnici = session_maker.query(Pracovnik).all()
    return render_template('pracovnici.html', pracovnici=pracovnici)

# Získání seznamu všech pracovníků (techniku)
@profile.route('/get-pracovnici')
def get_pracovnici():
    # Dotaz do databáze pro získání všech účtů s typem pracovník
    ucet_records = session_maker.query(Ucet).filter(Ucet.typ_uctu_id == 2).all()
    return jsonify([{ 'ucet_id': ucet.ucet_id, 'ucet_jmeno': ucet.ucet_jmeno } for ucet in ucet_records])

templates/__footer.jinja
<footer class="footer">
    <div class="footer-column">
        <h1>Kontaktní údaje</h1>
        <p>text</p>
    </div>
    <div class="footer-column">
        <h1>Adresa</h1>
        <p>text</p>
    </div>
</footer>

templates/__main.jinja
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Půjčovna strojů</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" type="text/css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500&display=swap" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    </head>

    <body>
        <!-- Include navigation -->
        {% include '__nav.jinja' %}

        <main>
            {% block content %}
            {% endblock %}
        </main>

        {% include '__footer.jinja' %}
    </body>
</html>

templates/__nav.jinja
{% block nav %}
    <div class="navigation">
        <div class="logo">LOGO</div>
        <div class="navigation-links">
            <a href="{{url_for('homepage.home')}}" onclick="toggleMenu()">Domů</a>
{#            <a href="{{url_for('views.onas')}}">O nás</a>#}
            <a href="{{url_for('order.nabidka_stroju')}}" onclick="toggleMenu()">Nabídka strojů</a>
            <!-- <a id="login" href="/prihlaseni" onclick="toggleMenu()">Přihlásit se</a> -->

            <!-- Pokud je uživatel dispečer -->
            {% if typ_uctu == 1 %}
            <a href="{{url_for('order.objednavky_k_potvrzeni')}}">Objednávky k potvrzeni</a>
            {% endif %}
            <!-- Pokud je uživatel technik -->
            {% if typ_uctu == 2 %}
            <a href="{{url_for('order.moje_zakazky')}}">Přiřazené objednávky</a>
            {% endif %}

            <!-- Pokud je uživatel přihlášen -->
            {% if user_name %}
            <a href="{{url_for('profile.profil')}}">{{ user_name }}</a>
            <a href="{{url_for('profile.odhlaseni')}}">Odhlásit se</a>
            {% else %}
            <a id="login" href="{{url_for('profile.prihlaseni')}}" onclick="toggleMenu()">Přihlásit se</a>
            {% endif %}
        </div>
        <div class="hamburger-menu" onclick="toggleMenu()">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>
    </div>
    <header></header>
{% endblock %}

templates/index.jinja
{% extends '/__main.jinja' %}

{% block content %}

    <!--Uvodni sekce-->
    <div class="hero-section">
        <div class="hero-text">
            <h1>Půjčovna strojů</h1>
            <h2>Zadejte vaše preference a doručíme vám stroj do druhého dne</h2>
        </div>
        <div class="form-section">
             <!--<form id="filter-form" method="POST" action="{{ url_for('views.home') }}">-->
            <div class="input-group">
                <label for="machine-type">Typ stroje:</label>
                <select id="machine-type">
                    <option value="default">Vyberte typ stroje</option>
                    <!-- Vyplnění zápisy z tabulky Typ_stroje -->
                    {% for typ_stroje_value in typ_stroje_values %}
                    <option value="{{ typ_stroje_value }}">{{ typ_stroje_value }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group">
                <label for="date-from">Od kdy:</label>
                <input type="date" id="date-from">
            </div>
            <div class="input-group">
                <label for="date-to">Do kdy:</label>
                <input type="date" id="date-to">
            </div>
            <button type="submit">OK</button>
             <!--</form>-->
            <div class="error-message"></div>
            <!--po vybrání by se měli vypsat věci zde-->
    <div class="output-group">
        {% for result in results %}
            <div class="input-group">
                <label for="machine-type">Typ stroje:</label>
                <p>{{ result.typ_stroje.typ }}</p>
            </div>
            <div class="input-group">
                <label for="date-from">Od kdy:</label>
                <p>{{ result.datum_od }}</p>
            </div>
            <div class="input-group">
                <label for="date-to">Do kdy:</label>
                <p>{{ result.datum_do }}</p>
            </div>
            <hr>
        {% endfor %}
    </div>

        </div>
    </div>

    <!--Jak to funguje sekce-->
    <div class="jak-to-fuguje">
        <h1>Jak to funguje?</h1>
        <div class="info-boxes">
            <div class="info-box">
                <div class="icon"><i class="fas fa-search"></i></div>
                <h3>Výběr stroje</h3>
                <p>Vyberte si stroj, který nejlépe vyhovuje vašim potřebám.</p>
            </div>
            <div class="info-box">
                <div class="icon"><i class="fas fa-calendar-alt"></i></div>
                <h3>Rezervace termínu</h3>
                <p>Zvolte datum, kdy chcete stroj půjčit.</p>
            </div>
            <div class="info-box">
                <div class="icon"><i class="fas fa-truck"></i></div>
                <h3>Doručení stroje</h3>
                <p>Stroj vám doručíme přímo na místo určení.</p>
            </div>
        </div>
    </div>

    <!--O nas sekce-->
    <div class="o-nas" id="o-nas">
        <div class="text-content">
            <h1>O nás</h1>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing
                elit.
                Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nunc tincidunt ante vitae massa. Mauris
                dictum facilisis augue.
                Etiam neque. Praesent vitae arcu tempor neque lacinia pretium. Duis pulvinar. Sed ut perspiciatis unde omnis
                iste natus error sit
                voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis
                et quasi architecto beatae
                vitae dicta sunt explicabo. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor
                sit amet purus malesuada congue.
                Nullam sit amet magna in magna gravida vehicula. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum
                at dui. In convallis.
                Mauris elementum mauris vitae tortor. </p>
        </div>
        <div class="image-content">
            <img src="/static/images/o-nas-image.jpg">
        </div>
    </div>
{% endblock %}

templates/nabidka-stroju.jinja
{% extends '/__main.jinja' %}

{% block content %}

    <div class="main-content">
        <div class="form-section">
            <div class="input-group">
                <label for="machine-type">Typ stroje:</label>
                <select id="machine-type">
                    <option value="default">Vyberte typ stroje</option>
                    <!-- Vyplnění zápisy z tabulky Typ_stroje -->
                    {% for typ_stroje_value in typ_stroje_values %}
                    <option value="{{ typ_stroje_value }}">{{ typ_stroje_value }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group">
                <label for="date-from">Od kdy:</label>
                <input type="date" id="date-from">
            </div>
            <div class="input-group">
                <label for="date-to">Do kdy:</label>
                <input type="date" id="date-to">
            </div>
            <button type="submit">OK</button>
            <div class="error-message"></div>
        </div>

        <div class="selected-values">
            <p>Typ stroje: <span id="display-machine"></span></p>
            <p>Od kdy: <span id="display-date-from"></span></p>
            <p>Do kdy: <span id="display-date-to"></span></p>
        </div>


        <div class="stroj-container">
            {% for stroj in stroje %}
            <div class="stroj-box">
                <h2>{{ stroj.stroj_nazev }}</h2>
                <p>Cena: {{ stroj.stroj_cena }} Kč</p>
                <p style="display: none;">Datum dostupnosti: {{ stroj.datum_dostupnosti }}</p>
                <p>{{ stroj.stroj_popis }}</p>
                {% if user_name %}
                <button class="reserve-button" onclick="toggleReserveForm('reserve-form-{{ stroj.stroj_id }}')">Zarezervovat</button>
                <div id="reserve-form-{{ stroj.stroj_id }}" style="display: none;">
                    <form action="/nabidka-stroju" method="post">
                        <input type="hidden" name="stroj_id" value="{{ stroj.stroj_id }}">
                        <input type="hidden" name="ucet_id" value="{{ ucet_id }}">
                        <input type="date" name="datum_od" placeholder="Datum od" required class="datum-rezervace">
                        <input type="date" name="datum_do" placeholder="Datum do" required class="datum-rezervace">
                        <input type="submit" value="Přidej Objednávku" class="button-rezervace">
                    </form>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/prihlaseni.jinja
{% extends '/__main.jinja' %}

{% block content %}

    <!-- Formular pro prihlaseni -->
    <div class="main-content">
      <div class="login-container">
        <h2>Přihlášení</h2>
        <form action="/prihlaseni" method="post">
          {{ form.hidden_tag() }}
          <div>
            {{ form.name.label }}
            {{ form.name(class="form-control") }}
          </div>
          <div>
            {{ form.password.label }}
            {{ form.password(class="form-control") }}
          </div>
          <div>
            {{ form.submit(class="btn btn-primary") }}
          </div>
          <div>
            <a href="/registrace">Vytvořit si účet</a>
          </div>
        </form>

      </div>
    </div>
{% endblock %}

templates/profil.jinja
{% extends '/__main.jinja' %}

{% block content %}

    <div class="main-content">
      <div class="rezervace-container">
        <h2>Moje Rezervace</h2>
        <table>
          <thead>
          <tr>
    <!--        <th>Rezervace ID</th>-->
            <th>Platnost</th>
            <!-- <th>Objednavka ID</th> -->
            <th>Datum Od</th>
            <th>Datum Do</th>
            <th>Stroj</th>
            <th>Přiřazený Pracovník</th> <!-- Updated header -->
            <th>Cena</th>
            <th>Akce</th>
          </tr>
          </thead>
          <tbody>
          {% for rezervace, datum_od, datum_do, stroj_nazev, stroj_cena, ucet_jmeno, cena in rezervace_records %}
          <tr>
    <!--        <td>{{ rezervace.rezervace_id }}</td>-->
            <td>
            {% if rezervace.rezervace_platnost %}
                Aktivní rezervace
            {% else %}
                Čeká na zrušení
            {% endif %}
            </td>
            <!-- <td>{{ rezervace.objednavka_id }}</td> -->
            <td>{{ datum_od }}</td>
            <td>{{ datum_do }}</td>
            <td>{{ stroj_nazev }}</td>
            <td>{{ ucet_jmeno }}</td> <!-- Replaced pracovnik_jmeno with ucet_jmeno -->
            <td>{{ cena }} Kč</td>
            <td>
              <form action="/zrusit_rezervaci" method="post">
                <input type="hidden" name="rezervace_id" value="{{ rezervace.rezervace_id }}">
                <button type="submit" class="cancel-reservation">Zrušit rezervaci</button>
              </form>
            </td>
          </tr>
          {% else %}
          <tr><td colspan="8">Žádné rezervace nebyly nalezeny.</td></tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
{% endblock %}

templates/registrace.jinja
{% extends '/__main.jinja' %}

{% block content %}

    <!-- Formular pro prihlaseni -->
    <div class="main-content">
      <div class="registration-form">
        <h2>Registrace</h2>
        <form method="POST" action="/registrace">
          {{ form.hidden_tag() }}
          <div>
            {{ form.name.label }}
            {{ form.name(class="form-control") }}
            {% for error in form.name.errors %}
            <p class="error">{{ error }}</p>
            {% endfor %}
          </div>
          <div>
            {{ form.email.label }}
            {{ form.email(class="form-control") }}
            {% for error in form.email.errors %}
            <p class="error">{{ error }}</p>
            {% endfor %}
          </div>
          <div>
            {{ form.password.label }}
            {{ form.password(class="form-control") }}
            {% for error in form.password.errors %}
            <p class="error">{{ error }}</p>
            {% endfor %}
          </div>
          <div>
            {{ form.submit(class="btn btn-primary") }}
          </div>
        </form>
      </div>
    </div>

{% endblock %}